use db_jugos;
SHOW TABLES;
SHOW COLUMNS FROM tbvendedores;
UPDATE tbvendedores SET porcentaje_comision = 0.08 WHERE matricula = "00235";
UPDATE tbvendedores SET porcentaje_comision = 0.08 WHERE matricula = "00236";
UPDATE tbvendedores SET porcentaje_comision = 0.08 WHERE porcentaje_comision = 8;
UPDATE tbvendedores SET porcentaje_comision = 11 WHERE matricula = "00236";
UPDATE tbvendedores SET nombre = "Joan Geraldo de la Fonseca Junior" WHERE matricula = "00233";
DELETE FROM tbvendedores WHERE matricula = "00233";
ALTER TABLE tbvendedores ADD PRIMARY KEY(matricula);
ALTER TABLE tbvendedores ADD COLUMN(fecha_admision DATE);
ALTER TABLE tbvendedores ADD COLUMN(de_vacaciones BIT);
UPDATE tbvendedores SET porcentaje_comision = 8, fecha_admision = "2014-08-15", de_vacaciones = 0 WHERE matricula = "00235";
UPDATE tbvendedores SET porcentaje_comision = 8, fecha_admision = "2013-09-17", de_vacaciones = 1 WHERE matricula = "00236";
INSERT INTO tbvendedores(matricula, nombre, porcentaje_comision, fecha_admision, de_vacaciones) VALUES ("00237", "Roberta Martins", 11, "2017-03-18", 1);
INSERT INTO tbvendedores(matricula, nombre, porcentaje_comision, fecha_admision, de_vacaciones) VALUES ("00238", "Péricles Alves", 11, "2016-08-21", 0);
SELECT * FROM tbvendedores;
SHOW COLUMNS FROM tbproductos;
INSERT INTO tbproductos(producto, nombre, envase, volumen, sabor, precio) VALUES ("773912", "clean", "botella pet", "1 litro", "naranja", 8.01);
INSERT INTO tbproductos(producto, nombre, envase, volumen, sabor, precio) VALUES ("838819", "clean", "botella pet", "1.5 litros", "naranja", 12.01);
INSERT INTO tbproductos(producto, nombre, envase, volumen, sabor, precio) VALUES ("1037997", "clean", "botella pet", "2 litros", "naranja", 16.01);
INSERT INTO tbproductos(producto, nombre, envase, volumen, sabor, precio) VALUES ("812829", "clean", "lata", "350 ml", "naranja", 2.81);
INSERT INTO tbvendedores(matricula, nombre, porcentaje_comision) VALUES ("00233", "Joan Geraldo de la Fonseca", 10);
INSERT INTO tbvendedores(matricula, nombre, porcentaje_comision) VALUES ("00235", "Márcio Almeida Silva", 8);
INSERT INTO tbvendedores(matricula, nombre, porcentaje_comision) VALUES ("00236", "Cláudia Morais", 8);
INSERT INTO tbproductos(producto, nombre, envase, volumen, sabor, precio) VALUES ('695594', 'Festival de Sabores', 'Botella PET',
'1.5 Litros', 'Asaí', 18.51);
INSERT INTO tbproductos(producto, nombre, envase, volumen, sabor, precio) VALUES ('1041119', 'Línea Citrus', 'Botella de Vidrio',
'700 ml', 'Lima', 4.90);
UPDATE tbproductos SET precio = 28.51 WHERE producto = "695594";
UPDATE tbproductos SET sabor = "Lima/Limón", precio = 4.90 WHERE producto = "1041119";
DELETE FROM tbproductos WHERE producto = "695594";
DELETE FROM tbproductos WHERE producto = "1041119";
ALTER TABLE tbproductos ADD PRIMARY KEY(producto);
INSERT INTO tbproductos(producto, nombre, envase, volumen, sabor, precio) VALUES ("773912", "clean", "botella pet", "1 litro", "naranja", 8.01);
SELECT * FROM tbproductos;
SHOW COLUMNS FROM tbclientes;
ALTER TABLE tbclientes ADD PRIMARY KEY(dni);
ALTER TABLE tbclientes ADD COLUMN(fecha_nacimiento DATE);
INSERT INTO tbclientes(dni, nombre, direccion1, direccion2, barrio, ciudad, estado, cp, edad, sexo, limite_credito, volumen_compra, primera_compra, fecha_nacimiento) VALUES ("456879548", "Pedro el Escamoso", "Calle del Sol, 25", "", "Los Laureles", "CDMX", "México", "65784", 55, "M", 1000000, 2000, 0, "1971-05-25");
SELECT * FROM tbclientes;
SHOW TABLES;
SELECT * FROM tbcliente;
SELECT * FROM tbproducto;
SELECT * FROM tbvendedores;
SELECT * FROM tbproducto LIMIT 4;
SELECT * FROM tbproducto WHERE sabor = "maracuya";
SELECT * FROM tbproducto WHERE envase = "botella de vidrio";
SELECT * FROM tbvendedores WHERE nombre = "Claudia Morais";